const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const c=vm.createContext({window:{addEventListener(){}},console});
vm.runInContext(fs.readFileSync('frontend/app.js','utf8').replace(/\ninit\(\);\s*$/,''),c);
const run=code=>vm.runInContext(code,c);
run(`currentDoc={title:'Run',notes:'',inputs:{datasets:[{name:'A',analysis_type:'xy',x:'1 2',y:'2 4',fit:{formula:'pol1'}}],active:0,formula:'pol1'},results:null};buildDocument=()=>currentDoc;markAnalysisSaved();`);
assert.equal(run('hasUnsavedAnalysis()'),false);
run("currentDoc.notes='New note'");assert.equal(run('hasUnsavedAnalysis()'),true);
run("currentDoc.notes=''");assert.equal(run('hasUnsavedAnalysis()'),false);
run('currentDoc.inputs.active=1;currentDoc.inputs.formula="gaus"');assert.equal(run('hasUnsavedAnalysis()'),false);
run("currentDoc.inputs.datasets[0].fit.formula='gaus'");assert.equal(run('hasUnsavedAnalysis()'),true);
run('markAnalysisSaved();currentDoc.results={params:[{value:2}]}');assert.equal(run('hasUnsavedAnalysis()'),true);
run('restoredUnsavedChanges=true;markAnalysisSaved()');assert.equal(run('hasUnsavedAnalysis()'),false);
run('restoredUnsavedChanges=true');assert.equal(run('hasUnsavedAnalysis()'),true);
let prevented=0; c.event={preventDefault(){prevented++;}};
run('warnBeforeLeaving(event)');assert.equal(prevented,1);assert.equal(c.event.returnValue,'');
run('markAnalysisSaved();warnBeforeLeaving(event)');assert.equal(prevented,1);
run(`datasets=currentDoc.inputs.datasets;tableDatasets=JSON.parse(JSON.stringify(datasets));tableActive=0;renderedGridSnapshot='original';gridSnapshot=()=> 'changed';`);
assert.equal(run('hasPendingTableEdits()'),true);
run('warnBeforeLeaving(event)');assert.equal(prevented,2);
run('gridSnapshot=()=> "original"');assert.equal(run('hasPendingTableEdits()'),false);
run('tableDatasets=null');assert.equal(run('hasPendingTableEdits()'),false);
console.log('OK: clean/edited/reverted documents, dataset selection, fit results, restored changes, pending table edits and leave-page warnings.');
c.URL=URL;
c.window.location={href:'https://example.test/tool/classic.html'};
c.clearTimeout=()=>{};c.setTimeout=()=>1;
run('autosaveNow=()=>true;restoredUnsavedChanges=true;');
assert.equal(run("isWorkspaceDestination('modern.html')"),true);
assert.equal(run("isWorkspaceDestination('index.html')"),true);
assert.equal(run("isWorkspaceDestination('https://other.test/modern.html')"),false);
assert.equal(run("isWorkspaceDestination('/different/modern.html')"),false);
const beforeInternal=prevented;
run("prepareWorkspaceNavigation('modern.html');warnBeforeLeaving(event)");
assert.equal(prevented,beforeInternal);
assert.equal(run('hasUnsavedAnalysis()'),true,'internal switching does not mark the analysis saved');
run('warnBeforeLeaving(event)');assert.equal(prevented,beforeInternal+1,'later closes still warn');
run("autosaveNow=()=>false;prepareWorkspaceNavigation('index.html');warnBeforeLeaving(event)");
assert.equal(prevented,beforeInternal+2,'failed persistence retains the warning');
console.log('OK: internal navigation preserves data without a warning; external navigation, later closes and storage failures retain protection.');
